# fly.toml app configuration file generated for cover-your-kittens-weathered-feather-7626 on 2025-01-19T19:44:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cover-your-kittens-weathered-feather-7626'
primary_region = 'den'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
